### ISSUE TITLE
Feature request: Prometheus / OpenMetrics metrics endpoint

### ISSUE THREAD

**Issue by junosuarez** [smlight-dev/slzb-06-firmware#21]
The prometheus / OpenMetrics metrics format is a simple, text-based way for Prometheus (and other monitoring tools) to collect status information over http - you can read more about it at https://scoutapm.com/blog/prometheus-metrics

The request is to add an http endpoint to the builtin server called `/metrics` that would return the same stats as the status page. This would make it easy to implement network monitoring, for example within a Grafana dashboard. 

Note, I am currently working on implementing the same in Zigbee2Mqtt, see https://github.com/Koenkk/zigbee2mqtt/issues/4521

**Comment by Tarik2142** [comment]
unclear protocol, I don't understand what the server should return

**Comment by junosuarez** [comment]
The server would return a text file with the metric names and current value. The spec documenting the various metric types is https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md

For example, I found that the current status page is getting an api response with some json like
```json
{
  "VERSION": "0.9.8 (Jan  2 2023)",
  "connectedSocketStatus": "Yes, 1 connections",
  "connectedSocket": "0 d 00:08:41",
  "operationalMode": "Zigbee-to-Ethernet",
  "ethDhcp": "On",
  "connectedEther": "Yes",
  "ethConnection": "Connected",
  "ethSpd": "100 Mbps",
  "ethIp": "10.10.8.4",
  "etchMask": "255.255.128.0",
  "ethGate": "10.10.8.1",
  "uptime": "0 d 00:53:57",
  "deviceTemp": "40.78",
  "hwRev": "SLZB-06",
  "espModel": "ESP32-D0WDQ5",
  "espCores": "2",
  "espFreq": "240",
  "espHeapFree": "221",
  "espHeapSize": "303",
  "espFlashType": "external",
  "espFlashSize": "16",
  "wifiEnabled": "No",
  "wifiConnected": "Not connected",
  "wifiMode": "Off",
  "wifiSsid": "Off",
  "wifiIp": "Off",
  "wifiSubnet": "Off",
  "wifiGate": "Off",
  "wifiRssi": "Off",
  "wifiDhcp": "Off",
  "wifiModeAP": "No",
  "wifiModeAPStatus": "Not started"
}
```

Depending on what the metrics are named, this could be represented like:
```
connected_socket_status=1
connected_socket_connections=1
connected_socket_uptime_seconds=521
connected_ether_status=1
connected_ether_speed_mbps=100
connected_ether_uptime_seconds=3237
device_temp=40.78
...
```
I'm not sure what other metrics would be interesting to expose - the uart socket connection status is the most interesting one for my needs. 

## Alternatives considered
I could create a separate process to scrape the  data as-is and reformat it as OpenMetrics. This is probably what I'll end up doing in the short term. However, it's less than perfect because it introduces another point of failure (the converter process). Best practice for simplicity and reliability is for services or devices to report their own metrics data directly.

**Comment by Tarik2142** [comment]
> connected_socket_status=1
connected_socket_connections=1
connected_socket_uptime_seconds=521
connected_ether_status=1
connected_ether_speed_mbps=100
connected_ether_uptime_seconds=3237
device_temp=40.78

Ok, now it's clear.

The device doesn't have many parameters that are updated often, so I think it makes sense to export only those parameters
![image](https://user-images.githubusercontent.com/31830530/229212834-94b6861e-1e14-49b8-9e2d-369f5dd9a3f2.png)

**Comment by Tarik2142** [comment]
@junosuarez check this build
[firmware.zip](https://github.com/smlight-dev/slzb-06-firmware/files/11141445/firmware.zip)
server endpoint **/metrics**
![image](https://user-images.githubusercontent.com/31830530/229598211-d862adcc-5692-4a1a-ab65-db09eef05041.png)

**Comment by fatpat** [comment]
Hi,

definetly the way to go. OpenMetrics export is a must have. It opens the door to the observability world (prometheus/alertmanager/grafana ... Name it)

and using an external exporter must be considered as an alternative way because including the exports directly in the soft is the best practice to ensure to always have metrics following changes in the code base.

**Comment by Tarik2142** [comment]
Hi, @junosuarez
Can you confirm that everything is right?

**Comment by onedr0p** [comment]
@Tarik2142 From that screen shot the metrics do not appear to be in the correct format.

Have you had a look here?

https://prometheus.io/docs/instrumenting/writing_exporters/

**Comment by onedr0p** [comment]
I didn't give the FW a try yet however, there should be a space in the output and it would be great if the metrics started with `smlight_` or some other unique identifier to help segregate the metrics from others that Prometheus consumes. e.g.

```
smlight_connected_socket_status{device="SLZB-06"}<space>1
```

**Comment by onedr0p** [comment]
Device name is actually not needed since Prometheus will add an instance label (with the IP address of the controller) to the metrics already.

**Comment by Tarik2142** [comment]
@onedr0p so is it done?
[firmware.zip](https://github.com/smlight-dev/slzb-06-firmware/files/11531338/firmware.zip)
![image](https://github.com/smlight-dev/slzb-06-firmware/assets/31830530/07a7e6a0-9029-4fe6-bedb-054f5006a67d)

**Comment by onedr0p** [comment]
I'll update my firmware today and test.

**Comment by onedr0p** [comment]
I put the zip here, correct?
<img width="583" alt="image" src="https://github.com/smlight-dev/slzb-06-firmware/assets/213795/52db1727-f5da-471a-b404-849dd2623838">

**Comment by Tarik2142** [comment]
First, unzip the archive, then click "Choose file" and start flashing

**Comment by onedr0p** [comment]
Almost there.. it looks like there might be some formatting issues on that metrics endpoint

<img width="1423" alt="image" src="https://github.com/smlight-dev/slzb-06-firmware/assets/213795/6b4cd4e2-6206-41e2-9301-6e95dc3162d6">

**Comment by onedr0p** [comment]
https://stackoverflow.com/questions/65388098/how-to-parse-prometheus-data

**Comment by Tarik2142** [comment]
@onedr0p yep, i use `\r\n` for line ending
check this fw [firmware.zip](https://github.com/smlight-dev/slzb-06-firmware/files/11531804/firmware.zip)

**Comment by onedr0p** [comment]
That's working now, any plans to add more metrics?

**Comment by Tarik2142** [comment]
@onedr0p what metrics do you need?

**Comment by bdd** [comment]
@Tarik2142 are you planning to push either the feature branch for openmetrics format and endpoint support to public repository, or maybe even merge it to `dev` branch?

I have a few more PRs coming soon, and I'd love to make it easier for you to not fight with a plethora of merge conflicts.

**Comment by Tarik2142** [comment]
@bdd Thanks for your PRs, I will try to update dev branch in the coming days so that you work with the current firmware.

**Comment by seandonohoo** [comment]
Can also confirm the firmware above is working great with prometheus :)

**Comment by xvisor16** [comment]
I can also confirm that it works! Sadly with this firmware the version of the zigbee firmware isn't visible anymore, also when trying to update zigbee it's says "Your current firmware revision: Unknown". I did manage to flash my coordinator firmware to the latest one. So that did work just fine.

**Comment by onedr0p** [comment]
Are there links to download the firmware instead for beta builds?

**Comment by xvisor16** [comment]
@Tarik2142, Thnx found it and flashed it. Working!
@onedr0p, You can find it on Github: https://github.com/smlight-dev/slzb-06-firmware/releases
But only use this if you are already running 1.0.0-dev!! Otherwise use the flasher as Tarik said!

**Comment by onedr0p** [comment]
> @onedr0p yep, i use `\r\n` for line ending check this fw [firmware.zip](https://github.com/smlight-dev/slzb-06-firmware/files/11531804/firmware.zip)

I last updated to this, does that mean I can use the Github release artifacts to upgrade?

**Comment by sergge1** [comment]
@onedr0p @xvisor16 is this done in the dev version? if yes, I will close. if no response within 24H I will close the issue as well.

**Comment by onedr0p** [comment]
I'm still unsure how to update being on the dev version, can you answer my last question?

**Comment by Tarik2142** [comment]
> I'm still unsure how to update being on the dev version, can you answer my last question?

If your current firmware version is less than 1.0, then firmware 1.0 or higher must be flashed via USB. If you have already flashed 1.0+ via USB, you can update via OTA to new firmware in the future.

**Comment by Tarik2142** [comment]
> I think my confusion is around being on the dev version which I did not flash via USB, so if I understand right I can flash the newer firmwares from the web UI?
> 
> My current version: <img alt="image" width="441" src="https://user-images.githubusercontent.com/213795/261406037-61828fc7-08a7-443f-a7ed-7240cd60feac.png">

You can use it like this, but Zigbee OTA updates will not work until you flash the firmware via USB

**Comment by onedr0p** [comment]
Ah that clears it up. I'll await for 1.0 to drop and flash it via USB.
Back to the issue here, I think this can be closed now... @junosuarez has appear to drop off the planet again:D

**Comment by xvisor16** [comment]
@sergge1 sorry for the late reaction, but yes!
