### ISSUE TITLE
WIFI access point is enabled

### ISSUE THREAD

**Issue by jwillmer** [smlight-dev/slzb-06-firmware#22]
How can I disable the access point? I only want `Zigbee to Ethernet` but I see that the device created a access point and can also see it in the status page:

![image](https://user-images.githubusercontent.com/1503577/230685019-f002d114-c820-444a-b0fa-bab2782c949a.png)

**Comment by jwillmer** [comment]
I figured it out. I did not set any `Subnet Mask` in the network config since the grayed one was already correct - and everything worked. Once I added the `Subnet Mask` manually the AP got disabled. There should be a validation for `Subnet Mask` if it is critical to set. And also a warning that AP is started since this is a security concern.

**Comment by Tarik2142** [comment]
@jwillmer Thanks for this info, it really looks like a validation is missed. This will be fixed in 1.0.0

**Comment by Tarik2142** [comment]
Fixed in https://github.com/smlight-dev/slzb-06-firmware/releases/tag/v1.0.0-dev
