### ISSUE TITLE
Feature Request: Remote Monitoring

### ISSUE THREAD

**Issue by villamanuel1980** [smlight-dev/slzb-06-firmware#24]
It would be very nice if the system reported when a socket client is disconnected. We're having issues with having to restart the zigbee and to manually monitor.

**Comment by rosiaantje** [comment]
Would love this function 2!
Both to monitor, notify and maybe even auto reset connection.. have once in a while no connection while z2m is still “thinking” it has.. so external monitoring would be highly appreciated!

**Comment by Tarik2142** [comment]
Hi all!
We already have a similar request
https://github.com/smlight-dev/slzb-06-firmware/issues/21

**Comment by Tarik2142** [comment]
Prometheus / OpenMetrics monitoring will be added in release 1.0
https://github.com/smlight-dev/slzb-06-firmware/issues/21
