### ISSUE TITLE
[Manuals Update] Flash without GUI

### ISSUE THREAD

**Issue by Ramalama2** [smlight-dev/slzb-06-firmware#27]
Hi, everything is great so far about this Stick!
Thanks Guys for making such a great PCB that covers everything!

I have just one request,
My Stick is in a location where its a pain in the ass to connect an usb cable to (To flash via usb)
Lets say we have to flash via USB to update from 0.99 to 1.0.0

So basically i had to connect an raspberry pi to the SLZB-06 Stick, and ssh onto the raspberry, clone the espflasher repository and flash from my computer over ssh from the pi the slzb stick :-)

The raspberry here has of course no gui.

That way should be described in the Manual either.

Another sidenote is: I have an M2 Macbook Pro with MacOS Ventura, the cp2102x driver isn't working on Ventura, at least not for the ARM (Apple Silicon) Plattform, maybe it does on the old intel X86_64 Platform, but however, the driver isn't working so you cant flash with MacOS.

Cheers

**Comment by Ramalama2** [comment]
I found another issue, it seems for me that an usb-c to usb-c connection doesn't work (i tryed with some laptops)
But usb-c to usb-a connection works perfectly fine.

Never seen such an issue, ive tryed with a definitively working c to c cable with what i flashed other esp's already.

**Comment by sylvaindd** [comment]
> I found another issue, it seems for me that an usb-c to usb-c connection doesn't work (i tryed with some laptops) But usb-c to usb-a connection works perfectly fine.
> 
> Never seen such an issue, ive tryed with a definitively working c to c cable with what i flashed other esp's already.

Same here for me, usb c-c doesn't work, usb c-a OK.

**Comment by Tarik2142** [comment]
> I have again and again this error: ![image](https://user-images.githubusercontent.com/16512337/252393464-d01a912b-6607-42b9-a34c-079a097fe980.png)
> 
> Tested USB A-C cable, resetting, holding and nothing :)

Try PC witch Intel chipset
OR
Short this pins for download mode
![image](https://github.com/smlight-dev/slzb-06-firmware/assets/31830530/4c7d7ebe-7d1a-4eb2-bba6-57b68488f483)

**Comment by S474N** [comment]
I have Intel chipset. But now have also problem with connecting to USB, there isn't visible device and no "windows sound" of connecting. After restart PC the same (also tested with another USB port). Must be also connected to ETH?

**Comment by S474N** [comment]
Will the software update be via USB or OTA in the future?

**Comment by Tarik2142** [comment]
If you have already flashed 1.0 via USB, then you can flash the following firmwares via OTA. USB flashing required only to update the partition table.

**Comment by S474N** [comment]
Also have problem with upgrading Coordinator firmware:
![image](https://github.com/smlight-dev/slzb-06-firmware/assets/16512337/5acd80ce-4f25-4851-ab95-3829a8efe92d)

![image](https://github.com/smlight-dev/slzb-06-firmware/assets/16512337/506998f7-8dbe-4646-9a0a-92fee841662f)

**Comment by S474N** [comment]
[sergge1](https://github.com/sergge1): step by step a couple of contributions higher, by short-circuiting two pins on the board. And yes, coordinator have access to internet.

**Comment by Tarik2142** [comment]
This error means that the coordinator does not have access to the Internet.
Are you using a static address?

**Comment by S474N** [comment]
Yes, static and trust me, have access to internet. How else would he find out that there is a new version for zigbee?

![image](https://github.com/smlight-dev/slzb-06-firmware/assets/16512337/5196991f-a52a-4033-9eaa-c2e13d685d94)

**Comment by sergge1** [comment]
I guess Taras trust you as i do, however that is the code of the error, e.g. error with that code can't appear  for some other reason

**Comment by S474N** [comment]
Is way, how can I check, that it have access to internet?

Or can I flash it with another way? (flasher link doesn't exists in doco).

**Comment by S474N** [comment]
OK, tested DHCP and another vlan :D  
![image](https://github.com/smlight-dev/slzb-06-firmware/assets/16512337/892a14c5-8ded-4b75-8bf8-334092ba71a8)

Now:
![image](https://github.com/smlight-dev/slzb-06-firmware/assets/16512337/dedcc20f-1488-45a5-a7d3-786bd4775e0c)
![image](https://github.com/smlight-dev/slzb-06-firmware/assets/16512337/b7c4b07c-61ff-4bef-ad30-e688ff38b871)

So thank you for cooperating!

**Comment by sergge1** [comment]
> OK, tested DHCP and another vlan :D
> 
> Now: !
> 
> So thank you for cooperating!

So what was the problem? Is it initial vlan or is it DHCP/Static?
Just to trace and try to reproduce and fix it if it relates to DHCP.
Meanwhile, I've updated the link to the flashing tool in the [manual](https://smlight.tech/manual/slzb-06/guide/flashing-and-updating/updating-cc2652p.html#over-the-air-ethernet-update); thank you for pointing me out.

**Comment by S474N** [comment]
Don't know, where is problem, because now have old VLAN and STATIC IP and it works:
![image](https://github.com/smlight-dev/slzb-06-firmware/assets/16512337/6eadbf50-7e94-4264-b892-1fb23b2a64bf)

**Comment by sergge1** [comment]
> Don't know, where is problem, because now have old VLAN and STATIC IP and it works:
May be it was some glitch with the network - e.g. not stable internet access . Thanks for feedback

**Comment by S474N** [comment]
I don't think it would be in the network, the connectivity is FTTH :D

![image](https://github.com/smlight-dev/slzb-06-firmware/assets/16512337/f888b8c5-1bcd-43af-8e34-46dff3c9c3db)

![image](https://github.com/smlight-dev/slzb-06-firmware/assets/16512337/823e345f-3049-46c4-9eb0-0a092109ae18)

**Comment by Tarik2142** [comment]
I think that you previously had an error in the subnet mask, so the coordinator had problems accessing the Internet. In this firmware update, the check of this field was fixed

**Comment by sergge1** [comment]
added information about documentation to the manual https://github.com/smlight-dev/slzb-06-manual/commit/26202dabab640dfd325345f761ea16f51554d3b8
