### ISSUE TITLE
Difference for ESP32 free heap

### ISSUE THREAD

**Issue by Nico83500** [smlight-dev/slzb-06-firmware#29]
Hi,
I just upgraded SLZB-06 from 0.9.9 to 1.0.0 (with ESP_Flasher, website flasher didn't work). It works but I would like to know why there is a difference between ESP32 free heap v0.9.9 (XXX / 296 KiB) and v1.0.0 (XXX / 287 KiB) ?
Thank you.

**Comment by Tarik2142** [comment]
Hi!
I think this is caused by changes in the partition table.
In 1.0, the size of the app partition was reduced in favor of the file system volume. This is needed to save the Zigbee firmware file for OTA

**Comment by Nico83500** [comment]
Hi, thank you ! So it seems to be normal, not a bug ;)
