### ISSUE TITLE
Correctly Recognize Ethernet Configuration Without Gateway

### ISSUE THREAD

**Issue by wapolinar** [smlight-dev/slzb-06-firmware#46]
When the device is configured without a gateway, it shows the following (although it is connected via ethernet) and turns on the AP:
![image](https://github.com/smlight-dev/slzb-06-firmware/assets/3637190/481cae9e-a79e-43c9-ad2e-d41d2698be09)
(note: I am connected via ethernet, here!)
![image](https://github.com/smlight-dev/slzb-06-firmware/assets/3637190/66633c55-468b-4533-89e3-85ccf8bb9a89)

As soon as some gateway is entered (IP, device does not need to exist), the device changes to the correct state and turns off the AP:
![image](https://github.com/smlight-dev/slzb-06-firmware/assets/3637190/ee5cc3c2-66f4-46bf-b54e-8d2162ea1dcc)
IP configuration (just a random IP for the gateway):
![image](https://github.com/smlight-dev/slzb-06-firmware/assets/3637190/83203798-7841-4c15-9b9f-e6459e5be22b)

Since the gateway is not required, it should be ignored and the AP should be turned off, even when there is no gateway entered.

**Comment by Tarik2142** [comment]
The gateway is necessary for the normal operation of the firmware.
Without a configured gateway, system events do not work correctly and the SYSTEM_EVENT_ETH_GOT_IP event is not called.
If you don't want to configure a gateway, you can use DHCP and reserve a static IP for the adapter on your router
