### ISSUE TITLE
SLZB-06 latest Der (1.0.1) Firmware?

### ISSUE THREAD

**Issue by clipse2004** [smlight-dev/slzb-06-firmware#53]
Hello all, 

At the moment I use the SLZB-06 with the dev version 1.0.0.
On your site it says something about Dev Version 1.0.1 but where can I find it? When I click on the link, it only says "Page not found". 
Were there problems with this version? Will it be online again?

Merci

**Comment by aurelmarius** [comment]
Same here.

**Comment by jesse-kaufman** [comment]
Still appears to be broken .. the online manual links to this repository talking about OTA updates, but there isn't a 1.0.x anywhere I can find. I'd love to be able to update my 2nd SLZB-06 with the firmware that supports OTA updates, as it's located out in my garage.

**Comment by Arn0uDz** [comment]
I'm running the 1.0.1 dev firmware (sadly I don't have the firmware.bin anymore) and today I experienced my first Z2M disconnect. That lead me to here and maybe i'm going to try downgrading if it keeps happening.

error 2023-09-06 00:29:12: Adapter disconnected, stopping
info  2023-09-06 00:29:12: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"offline"}'
info  2023-09-06 00:29:12: Disconnecting from MQTT server
info  2023-09-06 00:29:12: Stopping zigbee-herdsman...
error 2023-09-06 00:29:12: Failed to stop Zigbee2MQTT

**Comment by Tarik2142** [comment]
> I'm running the 1.0.1 dev firmware (sadly I don't have the firmware.bin anymore) and today I experienced my first Z2M disconnect. That lead me to here and maybe i'm going to try downgrading if it keeps happening.
> 
> error 2023-09-06 00:29:12: Adapter disconnected, stopping info 2023-09-06 00:29:12: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"offline"}' info 2023-09-06 00:29:12: Disconnecting from MQTT server info 2023-09-06 00:29:12: Stopping zigbee-herdsman... error 2023-09-06 00:29:12: Failed to stop Zigbee2MQTT

It looks like a network problem

**Comment by Tarik2142** [comment]
We are working on a new firmware version that will be available for download later. Stay tuned for updates in the repository
