### ISSUE TITLE
SLZB-06: Zigbee module unreachable until I restart it from WebUI

### ISSUE THREAD

**Issue by messageexplorer** [smlight-dev/slzb-06-firmware#68]
All Zigbee devices starts to be unavailable in Home Assistant, docker conteainer with Zigbee2Mqtt starts rebooting, and it can be fixed by rebooting Zigbee module on SLZB-06 WebUI. This issue happens second time during last 24 hours.

Maybe I can send any request to reboot Zigbee module on SLZB-06?

ESP32 Firmware ver:  0.9.9 (Mar 3 2023)
CC2652P version:  CC2652PP1FRGZR

**Comment by Dabbadoeber** [comment]
Same Here.
Suddenly stopped communicating with Z2M
While on the webpage is says socket connected.
Z2M Gives the following:

Using '/app/data' as data directory
Zigbee2MQTT:error 2023-11-07 22:45:02: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2023-11-07 22:45:02: Failed to start zigbee
Zigbee2MQTT:error 2023-11-07 22:45:02: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2023-11-07 22:45:02: Exiting...
Zigbee2MQTT:error 2023-11-07 22:45:02: Error: Failed to connect to the adapter (Error: SRSP - SYS - ping after 6000ms)
    at ZStackAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:103:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:60:27)
    at Controller.start (/app/lib/controller.ts:101:27)
    at start (/app/index.js:107:5)

Stopping the docker container wil result is socket not connected.

is this thing Broken ?

**Comment by Tarik2142** [comment]
It's not a socket problem, your zigbee chip is crashing. This can occur for various reasons: too many interference in the network, too many devices, a bug in the firmware.
There are also known cases when some devices spam packets in the Zigbee network and overload the coordinator

**Comment by messageexplorer** [comment]
And what I have to do now?

It is your zigbee coordinator, your bug in firmware.

**Comment by Tarik2142** [comment]
@messageexplorer Zigbee firmware for CC2652P is developed by Koen Kanters https://github.com/Koenkk/Z-Stack-firmware
Check recommendations for possible causes above

**Comment by messageexplorer** [comment]
Zigbee firmware can't be updated, because V 1.0 with this feature isn't
released yet.

Plus I asked how I can reboot zigbee module by direct api call, without Web
page.

**Comment by Tarik2142** [comment]
to rerest zigbee in fw 1.0 perform GET req http://DEVICE_IP/api?action=8&cmd=1
also you can try new 2.0 firmware https://smlight.tech/flasher/ that support zigbee OTA

**Comment by rsporsche** [comment]
I'm getting the same thing. Had it happen first in July, then again 8 days ago, now again today.

I tried 'Restart Zigbee' from the web interface but it didn't help. Doing 'Restart ESP32' did help.

Using firmware 0.9.9 with latest zigbee2mqtt on docker.
