### ISSUE TITLE
FW 2.0.5-dev The device freezes when trying to socket connect.

### ISSUE THREAD

**Issue by zvAndrey** [smlight-dev/slzb-06-firmware#71]
After updating to version 2.0.5, when trying to connect to Z2M, the web server starts to respond very slowly. The connection to the socket is also unsuccessful and ends with a timeout.
If you do not start the Z2M web server will work normally until you try to connect the socket.
I rolled back to version 2.0.3, on this version problem does not exist.

**Comment by Tarik2142** [comment]
Thanks for the quick report, indeed the conflict was caused by the DNS settings. As a temporary solution, I will disable it while I investigate.
