### ISSUE TITLE
How to flash to v.2.x using online flasher?

### ISSUE THREAD

**Issue by quantummobile** [smlight-dev/slzb-06-firmware#77]
Hey there,

I can't find any meaningful information anywhere on how to actually flash to v.2.x from v.0.9.9 using online flasher?
![Screenshot 2023-11-22 210812](https://github.com/smlight-dev/slzb-06-firmware/assets/47085307/dc4918b8-d56d-40ef-9e87-42265d4f20e3)
It only allows to flash to the same v 0.9.9 or lastes from 2.x branch, which I guess is wrong?

Very much look forward to hearing from you for support on this one.

Cheers

**Comment by Krazy998** [comment]
Just flash 2.0.8 it works fine

**Comment by neuhausf** [comment]
What are the changes in 2.0.8? I don't see any changelog.

**Comment by alexsalvo1** [comment]
You need a data cable otherwise it doesn’t appear as a device

**Comment by Coldness00** [comment]
Hello,
I use z2m and I would like to update to this new firmware.
Do I have to re pair all my devices afterward?
Thank you in advance.

**Comment by Arn0uDz** [comment]
> Hello, I use z2m and I would like to update to this new firmware. Do I have to re pair all my devices afterward? Thank you in advance.

I went from 0.9.9. to this and no need to re pair.
