### ISSUE TITLE
SLZB-06 log: task|[SOCK IP WHITELIST] Rejected connection from unknown IP: 128.100.252.63

### ISSUE THREAD

**Issue by hakong** [smlight-dev/slzb-06-firmware#80]
My SLZB-06's event log has quite a few of these entries. I've just booted it up an hour ago on my LAN - it is not exposed to the internet in any way.

`task|[SOCK IP WHITELIST] Rejected connection from unknown IP: 128.100.252.63`

Can I see more details about this somewhere? Timestamp?

**Comment by Krazy998** [comment]
The IP looks to be owned by a university. I believe it might be a timeserver. Note under time settings you can see that the ntp pool is configured. It possible the time server your SLZB resolved is down. I would suggest to use a more local pool in your area if possible.

**Comment by bikeymouse** [comment]
Isn’t the log about blocked incoming connections? Then it will not be a time server as that would be an outgoing connection.
Also if the SLZB is not connected to the internet “in any way” this can not be explained, so you better check if that is true.

**Comment by hakong** [comment]
> The IP looks to be owned by a university. I believe it might be a timeserver. Note under time settings you can see that the ntp pool is configured. It possible the time server your SLZB resolved is down. I would suggest to use a more local pool in your area if possible.

The IP is not a timeserver.
```
chronyc> sources
MS Name/IP address         Stratum Poll Reach LastRx Last sample
===============================================================================
^? 128.100.252.63                0   7     0     -     +0ns[   +0ns] +/-    0ns
```

The SLZB is configured to use the default pools `pool.ntp.org` and `time.google.com`.

Thats kinda besides the point as this (according to the logs) is an incoming connection to the socket. Why would a timeserver do that?

The SLZB is on a local network with no port forwarding rules.

>Also if the SLZB is not connected to the internet “in any way” this can not be explained, so you better check if that is true.

That's the reason I opened this issue. I'm not overly worried because this just _has_ to be incorrect. Could this be leftover log from when the firmware was built or something? A dev board exposed, firmware dumped, then uploaded to github with the logs?

Is there a way to see more about this somewhere? Configure log retention? Configure timestamps for the log format?

**Comment by Krazy998** [comment]
> Thats kinda besides the point as this (according to the logs) is an incoming connection to the socket. Why would a timeserver do that?

Agree - that doesn't make sense. I checked logs on my device after reflashing and I don't see them. You suggest a great point, which is that the log format should include timestamps. That perhaps should be a feature request (maybe syslog server support as well :-))

**Comment by hakong** [comment]
Where can I see the source code of this firmware?
The link to the latest 2.x firmware in the readme is to a youtube video - how strange?

All the firmware I can see in the repo is the "deprecated" 0.9.9 version.

**Comment by hakong** [comment]
As for now I've remove all internet access to and from the SLZB. I've tcpdumped its traffic for a while and couldn't see anything to or from the internet except for stats.smlight.tech, but that traffic is encrypted.

**Comment by smlight-dev-223942** [comment]
hi Hakong, the device can initiate an OUTGOING connection ONLY in three cases and ONLY if they are allowed by the user (in respective settings):
1) to sync time settings, if this is ENABLED by the user in Time setting tab.
2) to send info about the FW version used if this is ENABLED by the user in general settings tab.
3) if you submit a bug report via the web interface (obviously)
The device can not initiate the INCOMING connection. 
IP blocked by the device - is an INCOMING connection.
If you have any further questions, please send us an email. This repository is dedicated to fw 0.9.9.

`All the firmware I can see in the repo is the "deprecated" 0.9.9 version.`

FW 0.9.9 is not deprecated. It is stable and works. 2.x is not a successor of 0.9 - it is a completely new development based on our new architecture that is being implemented in all our devices (like upcoming [window opener](https://smlight.tech/product/window-opener/) etc), with cloud access and so on.

**Comment by hakong** [comment]
>The device can not initiate the INCOMING connection.
>IP blocked by the device - is an INCOMING connection.

This is exactly why I opened this issue. These log messages are _very_ strange to me. They have to be spurious - but still, they are generated somehow. Bug in the logger?

Are logs kept anywhere persistent? I rebooted the slzb and the logs are empty now.


I emailed the IP abuse contact for more info.

**Comment by Tarik2142** [comment]
> > The device can not initiate the INCOMING connection.
> > IP blocked by the device - is an INCOMING connection.
> 
> This is exactly why I opened this issue. These log messages are _very_ strange to me. They have to be spurious - but still, they are generated somehow. Bug in the logger?
> 
> Are logs kept anywhere persistent? I rebooted the slzb and the logs are empty now.
> 
> I emailed the IP abuse contact for more info.

I don't know what this IP is, it doesn't belong to us.
I think it has something to do with ZHA. Try Z2M, I think it won't generate additional connections from other IPs
