### ISSUE TITLE
What data is sent in the "non-sensitive analytics"?

### ISSUE THREAD

**Issue by hakong** [smlight-dev/slzb-06-firmware#83]
The page says "unique device ID and device type and installed firmware versions only."

I was not able to verify this.

tcpdumping the traffic from the SLZB shows encrypted traffic to https://stats.smlight.tech/.

I have not done SSL stripping or decryption on the traffic yet. Maybe I'm lucky and the SLZB does not have strict certificate verification.

**Comment by hakong** [comment]
I would absolutely have this setting turned on if I could see what it does.

**Comment by Tarik2142** [comment]
> Tarik2142 [notifications@github.com](mailto:notifications@github.com) 11 Dec 2023, 12:57 (20 hours ago)
> 
> > MAC (SHA-256 hash)
> > device model (06 or 06M)
> > main MCU (ESP32)
> > main fw version (2.0.8 or another)
> > secondary MCU (EFR32 or CC2652P)
> > secondary MCU fw version
> > As you can see, there is no confidential information here, only statistical data
> 
> This technically answers my question but it's a "trust me" answer. I have to take your word for it, there's no way for me to verify this.
> 
> And why was the comment deleted?
> 
> This is terrible attitude towards legitimate questions from the community. Quite a few people are asking questions around development, behavior, open sourcing the code, etc.. but you keep closing issues quickly without addressing the underlying issue.

Friend, I'm writing code, not moderating comments.
I can answer technical questions, if you have other questions, you can write to **info@smartlight.me**
In general, this repository is for firmware 0.9.9 and I'm not sure if it's correct to address 2.0 here.
Starting with 2.0.8, everyone has the ability to submit a bug report or request directly from the coordinator web interface, so 2.0 does not currently require a bug report repository
